openapi: 3.0.2
info:
  title: API for Auth & Identity domain
  description: Mobile and web backend API for the Auth and Identity domain.
  version: 16.7.0
servers:
  - url: https://api-app.io.pagopa.it
security:
  - Bearer: []
paths:
  /api/v1/services/{service_id}/preferences:
    get:
      summary: GetServicePreferences
      operationId: getServicePreferences
      parameters:
        - name: service_id
          in: path
          description: The ID of an existing Service.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Service Preference found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServicePreference"
              example:
                can_access_message_read_status: true
                is_inbox_enabled: true
                is_email_enabled: false
                is_webhook_enabled: true
                settings_version: 1
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Unauthorized
          content: {}
        "404":
          description: No service found for the provided ID.
          content: {}
        "409":
          description: Conflict. The Profile is not in the correct preference mode.
          content: {}
        "429":
          description: Too many requests
          content: {}
        "500":
          description: Internal Server Error
          content: {}
    post:
      summary: UpsertServicePreferences
      operationId: upsertServicePreferences
      parameters:
        - name: service_id
          in: path
          description: The ID of an existing Service.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertServicePreference"
        required: false
      responses:
        "200":
          description: Service Preference found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServicePreference"
              example:
                can_access_message_read_status: true
                is_inbox_enabled: true
                is_email_enabled: false
                is_webhook_enabled: true
                settings_version: 1
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Unauthorized
          content: {}
        "404":
          description: No service found for the provided ID.
          content: {}
        "409":
          description: |-
            Conflict. Either the provided preference setting version is not consistent with the current version stored in the Profile
            or the Profile is not in the correct preference mode.
          content: {}
        "429":
          description: Too many requests
          content: {}
        "500":
          description: Internal Server Error
          content: {}
  /api/v1/profile:
    get:
      summary: Get user's profile
      description:
        Returns the profile for the user identified by the provided fiscal
        code.
      operationId: getUserProfile
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitializedProfile"
              example:
                email: email@example.com
                family_name: Rossi
                fiscal_code: TMMEXQ60A10Y526X
                has_profile: true
                is_email_set: true
                is_inbox_enabled: true
                is_webhook_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                name: Mario
                spid_email: preferred@example.com
                service_preferences_settings:
                  - mode: LEGACY
                version: 1
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the user profile.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
    post:
      summary: Update the User's profile
      description:
        Update the profile for the user identified by the provided fiscal
        code.
      operationId: updateProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Profile"
        required: true
      responses:
        "200":
          description: Profile updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitializedProfile"
              example:
                email: email@example.com
                family_name: Rossi
                fiscal_code: TMMEXQ60A10Y526X
                has_profile: true
                is_email_set: true
                is_inbox_enabled: true
                is_webhook_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                name: Mario
                spid_email: preferred@example.com
                version: 0
        "400":
          description: Invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "409":
          description: Conflict.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "412":
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: Profile cannot be updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /api/v1/api-profile:
    get:
      summary: Get user's profile stored into the API
      description:
        Returns the profile for the user identified by the provided fiscal
        code.
      operationId: getApiUserProfile
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtendedProfile"
              example:
                email: email@example.com
                preferred_languages:
                  - it_IT
                is_inbox_enabled: true
                accepted_tos_version: 1
                is_webhook_enabled: true
                is_email_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                version: 1
                sender_allowed: true
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "404":
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the user profile.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /api/v1/email-validation-process:
    post:
      summary: Start the Email Validation Process
      description: |-
        Start the email validation process that create the validation token
        and send the validation email
      operationId: startEmailValidationProcess
      responses:
        "202":
          description: Accepted
          content: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "404":
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error starting email validation process
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /api/v1/sessions:
    get:
      summary: List sessions of a User
      description: Return all the active sessions for an authenticated User.
      operationId: listUserSessions
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionsList"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "500":
          description: Unavailable service
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /api/v1/user-data-processing:
    post:
      summary: Set User's data processing choices
      description:
        Let the authenticated user express his will to retrieve or delete
        his stored data.
      operationId: upsertUserDataProcessing
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDataProcessingChoiceRequest"
        required: true
      responses:
        "200":
          description: User Data processing created / updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataProcessing"
        "400":
          description: Invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
          content: {}
        "409":
          description: Conflict.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too may requests
          content: {}
        "500":
          description: User Data processing choice cannot be taken in charge.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /api/v1/user-data-processing/{choice}:
    get:
      summary: Get User's data processing
      description:
        Get the user's request to delete or download his stored data by
        providing a kind of choice.
      operationId: getUserDataProcessing
      parameters:
        - name: choice
          in: path
          description: A representation of a user data processing choice
          required: true
          schema:
            type: string
            enum:
              - DOWNLOAD
              - DELETE
      responses:
        "200":
          description: User data processing retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataProcessing"
        "401":
          description: Bearer token null or expired.
          content: {}
        "404":
          description: Not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content: {}
    delete:
      tags:
        - restricted
      summary: Abort User's revious data processing request
      description: "Ask for a request to abort, if present"
      operationId: abortUserDataProcessing
      parameters:
        - name: choice
          in: path
          description: A representation of a user data processing choice
          required: true
          schema:
            type: string
            enum:
              - DOWNLOAD
              - DELETE
      responses:
        "202":
          description: The abort request has been recorded
          content: {}
        "400":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Unauthorized
          content: {}
        "404":
          description: Not Found
          content: {}
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content: {}
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /first-lollipop/sign:
    post:
      operationId: signMessage
      summary: POST a signed request with Lollipop
      parameters:
        - name: x-pagopa-lollipop-original-method
          in: header
          description: The method of the endpoint called by IO app
          required: true
          schema:
            $ref: "#/components/schemas/LollipopMethod"
        - name: x-pagopa-lollipop-original-url
          in: header
          description: The url of the endpoint called by IO app
          required: true
          schema:
            $ref: "#/components/schemas/LollipopOriginalURL"
        - name: content-digest
          in: header
          description: The body digest, if any, as defined in https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-10
          required: true
          schema:
            $ref: "#/components/schemas/LollipopContentDigest"
        - name: signature-input
          in: header
          description: The signature input, needed to verify the `signature` header
          required: true
          schema:
            $ref: "#/components/schemas/LollipopSignatureInput"
        - name: signature
          in: header
          description: The signature of the HTTP request, signed by the client with its private key.
          required: true
          schema:
            $ref: "#/components/schemas/LollipopSignature"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignMessagePayload"
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignMessageResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Token null or invalid.
        "500":
          description: There was an error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"

components:
  schemas:
    # Definitions from the digital citizenship APIs
    AcceptedTosVersion:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/AcceptedTosVersion"
    AppVersion:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/AppVersion"
    BlockedInboxOrChannels:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/BlockedInboxOrChannels"
    DepartmentName:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/DepartmentName"
    EmailAddress:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/EmailAddress"
    PreferredLanguage:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PreferredLanguage"
    PreferredLanguages:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PreferredLanguages"
    Profile:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Profile"
    ExtendedProfile:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ExtendedProfile"
    FiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/FiscalCode"
    IsEmailEnabled:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsEmailEnabled"
    IsInboxEnabled:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsInboxEnabled"
    IsEmailValidated:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsEmailValidated"
    IsEmailAlreadyTaken:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsEmailAlreadyTaken"
    UpdateProfile412ErrorTypes:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/refs/tags/v29.3.0/openapi/problemJson_definitions.yaml#/UpdateProfile412ErrorTypes"
    ReminderStatus:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ReminderStatus"
    PushNotificationsContentType:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PushNotificationsContentType"
    IsTestProfile:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsTestProfile"
    IsWebhookEnabled:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/IsWebhookEnabled"
    LimitedProfile:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/LimitedProfile"
    MessageResponseNotificationStatus:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageResponseNotificationStatus"
    NotificationChannelStatusValue:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/NotificationChannelStatusValue"
    NotificationChannel:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/NotificationChannel"
    OrganizationFiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/OrganizationFiscalCode"
    OrganizationName:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/OrganizationName"
    ProblemJson:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ProblemJson"
    ServiceId:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServiceId"
    ServiceCategory:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServiceCategory"
    SpecialServiceCategory:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/SpecialServiceCategory"
    StandardServiceCategory:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/StandardServiceCategory"
    Timestamp:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Timestamp"
    PaymentNoticeNumber:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentNoticeNumber"
    PaymentAmount:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentAmount"
    PaymentData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentData"
    TimeToLiveSeconds:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/TimeToLiveSeconds"
    UserDataProcessingStatus:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/UserDataProcessingStatus"
    UserDataProcessingChoice:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/UserDataProcessingChoice"
    UserDataProcessingChoiceRequest:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/UserDataProcessingChoiceRequest"
    UserDataProcessing:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/UserDataProcessing"
    ServicePreferencesSettings:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServicePreferencesSettings"
    ServicesPreferencesMode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServicesPreferencesMode"
    BasicServicePreference:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/BasicServicePreference"
    ServicePreference:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServicePreference"
    UpsertServicePreference:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/UpsertServicePreference"
    PaginationResponse:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaginationResponse"
    Ulid:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Ulid"
    PathTraversalSafePathParam:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PathTraversalSafePathParam"
    # AssertionRef possible inputs
    AssertionRefSha256:
      type: string
      pattern: ^(sha256-[A-Za-z0-9-_=]{1,44})$
    AssertionRefSha384:
      type: string
      pattern: ^(sha384-[A-Za-z0-9-_=]{1,66})$
    AssertionRefSha512:
      type: string
      pattern: ^(sha512-[A-Za-z0-9-_=]{1,88})$
    AssertionRef:
      x-one-of: true
      allOf:
        - $ref: "#/components/schemas/AssertionRefSha512"
        - $ref: "#/components/schemas/AssertionRefSha384"
        - $ref: "#/components/schemas/AssertionRefSha256"
    InitializedProfile:
      type: object
      title: Initialized profile
      description: Describes the user's profile after it has been stored in the Profile API.
      properties:
        accepted_tos_version:
          $ref: "#/components/schemas/AcceptedTosVersion"
        email:
          $ref: "#/components/schemas/EmailAddress"
        blocked_inbox_or_channels:
          $ref: "#/components/schemas/BlockedInboxOrChannels"
        preferred_languages:
          $ref: "#/components/schemas/PreferredLanguages"
        is_inbox_enabled:
          $ref: "#/components/schemas/IsInboxEnabled"
        is_email_validated:
          $ref: "#/components/schemas/IsEmailValidated"
        is_email_already_taken:
          $ref: "#/components/schemas/IsEmailAlreadyTaken"
        is_email_enabled:
          $ref: "#/components/schemas/IsEmailEnabled"
        reminder_status:
          $ref: "#/components/schemas/ReminderStatus"
        push_notifications_content_type:
          $ref: "#/components/schemas/PushNotificationsContentType"
        is_webhook_enabled:
          $ref: "#/components/schemas/IsWebhookEnabled"
        family_name:
          type: string
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
        has_profile:
          $ref: "#/components/schemas/HasProfile"
        last_app_version:
          $ref: "#/components/schemas/AppVersion"
        name:
          type: string
        spid_email:
          $ref: "#/components/schemas/EmailAddress"
        date_of_birth:
          type: string
          format: date
        service_preferences_settings:
          $ref: "#/components/schemas/ServicePreferencesSettings"
        version:
          $ref: "#/components/schemas/Version"
      required:
        - family_name
        - fiscal_code
        - has_profile
        - is_inbox_enabled
        - is_email_enabled
        - is_webhook_enabled
        - name
        - service_preferences_settings
        - version
    SessionInfo:
      type: object
      title: Session info of a user
      description: Decribe a session of an authenticated user.
      properties:
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        sessionToken:
          type: string
      required:
        - createdAt
        - sessionToken
    SessionsList:
      description: Contains all active sessions for an authenticated user.
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: "#/components/schemas/SessionInfo"
      required:
        - sessions
    HasProfile:
      type: boolean
      default: false
      description: True if the user has a remote profile.
    IsEmailSet:
      type: boolean
      default: false
      description: True if the user has presonalized the email.
    Version:
      type: integer
      description: The entity version.
    SpidLevel:
      type: string
      description: A SPID level.
      x-extensible-enum:
        - https://www.spid.gov.it/SpidL1
        - https://www.spid.gov.it/SpidL2
        - https://www.spid.gov.it/SpidL3
    LimitedFederatedUser:
      title: Federated user
      description: User data needed by federated applications.
      type: object
      properties:
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
      required:
        - fiscal_code
    FederatedUser:
      title: Federated user
      description: User data needed by federated applications.
      allOf:
        - type: object
          properties:
            name:
              type: string
            family_name:
              type: string
          required:
            - name
            - family_name
        - $ref: "#/components/schemas/LimitedFederatedUser"
    LollipopMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    LollipopOriginalURL:
      type: string
      pattern: "^https:\/\/"
    LollipopContentType:
      type: string
      enum:
        - application/json
        - application/octet-stream
    LollipopContentDigest:
      type: string
      pattern: "^(sha-256=:[A-Za-z0-9+/=]{44}:|sha-384=:[A-Za-z0-9+/=]{66}:|sha-512=:[A-Za-z0-9+/=]{88}:)$"

    LollipopSignatureInput:
      type: string
      pattern: ^(?:sig\d+=[^,]*)(?:,\s*(?:sig\d+=[^,]*))*$
    LollipopSignature:
      type: string
      pattern: ^((sig[0-9]+)=:[A-Za-z0-9+/=]*:(, ?)?)+$

    SignMessagePayload:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    SignMessageResponse:
      type: object
      properties:
        response:
          type: string

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
