openapi: 3.0.2
info:
  version: 1.0.0
  title: IO Communication API
  description: |
    API for managing user messages, notifications and payment information.
servers:
  - url: https://localhost/api/communication/v1
security:
  - Bearer: []
paths:
  /messages:
    get:
      operationId: getUserMessages
      summary: Get user's messages
      description: |-
        Returns the messages for the user identified by the provided fiscal code.
        Messages will be returned in inverse acceptance order (from last to first).
        The "next" field, when present, contains an URL pointing to the next page of results.
      parameters:
        - $ref: "#/components/parameters/PageSize"
        - $ref: "#/components/parameters/EnrichResultData"
        - $ref: "#/components/parameters/GetArchivedMessages"
        - $ref: "#/components/parameters/MaximumId"
        - $ref: "#/components/parameters/MinimumId"
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedPublicMessagesCollection"
              example:
                items:
                  - created_at: "2018-05-21T07:36:41.209Z"
                    fiscal_code: "LSSLCU79B24L219P"
                    id: "01CE0T1Z18T3NT9ECK5NJ09YR3"
                    sender_service_id: "5a563817fcc896087002ea46c49a"
                    time_to_live: 3600
                  - created_at: "2018-05-21T07:41:01.361Z"
                    fiscal_code: "LSSLCU79B24L219P"
                    id: "01CE0T9X1HT595GEF8FH9NRSW7"
                    sender_service_id: "5a563817fcc896087002ea46c49a"
                    time_to_live: 3600
                next: 01CE0T9X1HT595GEF8FH9NRSW7
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "404":
          description: No message found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the messages.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /messages/{id}:
    get:
      operationId: getUserMessage
      summary: Get message
      description: |-
        Returns the message with the provided message ID.
      parameters:
        - $ref: "#/components/parameters/MessageId"
        - $ref: "#/components/parameters/PublicMessage"
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedMessageWithContentAndAttachments"
              example:
                content:
                  markdown: "hey hey !! <a style=\"color: red\" href=\"http://example.com\"> some content here ..... this is a link with a style applied, some other content</a>"
                  subject: "my subject ............"
                  attachments:
                    - name: "attachment"
                      content: "aBase64Encoding"
                      mime_type: "image/png"
                created_at: "2018-06-06T12:22:24.523Z"
                fiscal_code: "LSSLCU79B24L219P"
                id: "01CFAGRMGB9XCA8B2CQ4QA7K76"
                sender_service_id: "5a25abf4fcc89605c082f042c49a"
                time_to_live: 3600
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "404":
          description: No message found for the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the message.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /messages/{id}/status:
    put:
      operationId: upsertMessageStatusAttributes
      summary: UpsertMessageStatusAttributes
      description: Updates the status of a message with attributes
      parameters:
        - $ref: "#/components/parameters/MessageId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageStatusChange"
            example:
              change_type: "bulk"
              is_archived: true
              is_read: true
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageStatusAttributes"
              example:
                is_read: true
                is_archived: false
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Operation forbidden.
        "404":
          description: No message found for the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in upserting message's status attributes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  
  # Third Party Messages
  /third-party-messages/{id}/precondition:
    get:
      operationId: getRemoteContentPrecondition
      summary: Retrieve third party message precondition
      description: |-
        Returns the precondition associated to the provided message ID to receive the third party message.
      parameters:
        - $ref: "#/components/parameters/MessageId"
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ThirdPartyMessagePrecondition"
              example:
                title: "Questo messaggio contiene una comunicazione a valore legale"
                markdown: "Se continui, la notifica risulter√† legalmente recapitata a te. Aprire il messaggio su IO equivale infatti a firmare la ricevuta di ritorno di una raccomandata tradizionale.\n**Mittente**: Comune di Xxxxxxx  \n**Oggetto**: Infrazione al codice della strada  \n**Data e ora**: 12 Luglio 2022 - 12.36  \n**Codice IUN**: YYYYMM-1-ABCD-EFGH-X"
        "204":
          description: Pre conditions not needed
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden
        "404":
          description: No message found for the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "410":
          description: Third Party Service no longer available
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the message.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        '501':
          description: Not Implemented
        '504':
          description: Gateway Timeout
  /third-party-messages/{id}:
    get:
      operationId: getRemoteContent
      summary: Retrieve third party message
      description: |-
        Returns the third party message with the provided message ID.
      parameters:
        - $ref: "#/components/parameters/MessageId"
      responses:
        "200":
          description: Found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ThirdPartyMessageWithContent"
              example:
                content:
                  markdown: "hey hey !! <a style=\"color: red\" href=\"http://example.com\"> some content here ..... this is a link with a style applied, some other content</a>"
                  subject: "my subject ............"
                  third_party_data:
                    - id: "aThirdPartyMessageId"
                third_party_message:
                  attachments: []
                  custom_property: "a custom property"
                created_at: "2018-06-06T12:22:24.523Z"
                fiscal_code: "LSSLCU79B24L219P"
                id: "01CFAGRMGB9XCA8B2CQ4QA7K76"
                sender_service_id: "5a25abf4fcc89605c082f042c49a"
                time_to_live: 3600
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden
        "404":
          description: No message found for the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "410":
          description: Third Party Service no longer available
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "500":
          description: There was an error in retrieving the message.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        '501':
          description: Not Implemented
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        '504':
          description: Gateway Timeout
  /third-party-messages/{id}/attachments/{attachment_url}:
    get:
      operationId: getRemoteContentAttachment
      summary: Retrieve an attachment of a third party message
      parameters:
        - $ref: "#/components/parameters/MessageId"
        - name: attachment_url
          in: path
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: Success
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: No message found for the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "410":
          description: Third Party Service no longer available
        "415":
          description: Unsupported Media TYPE - File Format Validation Error
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
        '501':
          description: Not Implemented
        '504':
          description: Gateway Timeout
  
  # SEND Activation
  /send/activation:
    get:
      operationId: getSendActivation
      summary: Get SEND Activation
      description: |
        Get the service activation status for Special Service "Avvisi di Cortesia"
      parameters:
        - name: isTest
          in: query
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Request created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendActivation"
        "401":
          description: Bearer token null or expired.
        "429":
          description: Too many requests
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
    post:
      operationId: upsertSendActivation
      summary: Upsert SEND Activation
      description: |
        Upsert the service activation status for Special Service "Avvisi di Cortesia"
      parameters:
        - name: isTest
          in: query
          required: false
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendActivation'
            example:
              activation_status: true
      responses:
        "204":
          description: Request created.
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "401":
          description: Bearer token null or expired.
        "429":
          description: Too many requests
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  
  # Installation
  /installations/{installationID}:
    put:
      operationId: createOrUpdateInstallation
      summary: Create or update an Installation
      description: Create or update an Installation to the Azure Notification hub.
      parameters:
        - name: installationID
          in: path
          required: true
          description: The ID of the installation.
          schema:
            $ref: "#/components/schemas/InstallationID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Installation"
            example:
              platform: "gcm"
              pushChannel: "push-notification-service-handle"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
              example:
                message: "ok"
        "401":
          description: Bearer token null or expired.
        "500":
          description: There was an error in registering the device to the Notification Hub.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  
  # Payment Info
  /payment/info/{rptId}:
    get:
      operationId: getPaymentInfoV2
      summary: Get Payment Info
      description: Retrieve information about a payment
      parameters:
        - name: rptId
          in: path
          required: true
          description: Unique identifier for payments.
          schema:
            type: string
        - name: test
          in: query
          description: Use test environment of PagoPAEcommerceClient
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Payment information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfoResponse"
              example:
                amount: 11400
                description: "PAGAMENTO TARI PRIMA RATA"
                dueDate: "2025-05-31"
        "401":
          description: Bearer token null or expired.
        "404":
          description: This error occurs when submitting a non-existing RPT id.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfoNotFoundResponse"
        "409":
          description: Conflict on payment status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfoConflictResponse"
        "500":
          description: Unauthorized, access token missing or invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        "502":
          description: PagoPA services are not available or request is rejected by PagoPa
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfoBadGatewayResponse"
        "503":
          description: EC services are not available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfoUnavailableResponse"

components:
  parameters:
    MessageId:
      name: id
      in: path
      required: true
      description: The message id in ulid format
      schema:
        type: string
        maxLength: 26
        minLength: 26
        pattern: "[0-9a-hjkmnp-tv-zA-HJKMNP-TV-Z]{26}"
      example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
    PublicMessage:
      name: public_message
      in: query
      description: Discriminate when to return public message shape. Default to false.
      schema:
        type: boolean
    EnrichResultData:
      name: enrich_result_data
      in: query
      required: false
      description: Indicates whether result data should be enriched or not.
      schema:
        type: boolean
    GetArchivedMessages:
      name: archived
      in: query
      required: false
      description: Indicates whether retrieve archived/not archived messages. Default is false
      schema:
        type: boolean
    PageSize:
      name: page_size
      in: query
      required: false
      description: How many items a page should include.
      schema:
        type: integer
        minimum: 1
        maximum: 100
    MaximumId:
      name: maximum_id
      in: query
      required: false
      description: The maximum id to get messages until to.
      schema:
        type: string
        maxLength: 26
        minLength: 26
        pattern: "[0-9a-hjkmnp-tv-zA-HJKMNP-TV-Z]{26}"
      example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
    MinimumId:
      name: minimum_id
      in: query
      required: false
      description: The minimum id to get messages from.
      schema:
        type: string
        maxLength: 26
        minLength: 26
        pattern: "[0-9a-hjkmnp-tv-zA-HJKMNP-TV-Z]{26}"
      example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
  schemas:
    # Definitions from io-functions-commons
    FiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/FiscalCode"
    OrganizationFiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/OrganizationFiscalCode"
    Timestamp:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Timestamp"
    TimeToLiveSeconds:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/TimeToLiveSeconds"
    ProblemJson:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ProblemJson"
    PublicMessage:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PublicMessage"
    PaginationResponse:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaginationResponse"
    PublicMessagesCollection:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PublicMessagesCollection"
    PaginatedPublicMessagesCollection:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaginatedPublicMessagesCollection"
    EnrichedMessage:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/EnrichedMessage"
    BaseEnrichedMessage:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/BaseEnrichedMessage"
    MessageStatusAttributes:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageStatusAttributes"
    CreatedMessageWithoutContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithoutContent"
    CreatedMessageWithoutContentCollection:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithoutContentCollection"
    NewMessageContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/NewMessageContent"
    MessageContentBase:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageContentBase"
    MessageBodyMarkdown:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageBodyMarkdown"
    MessageSubject:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageSubject"
    EUCovidCert:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/EUCovidCert"
    Payee:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Payee"
    PaymentDataBase:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentDataBase"
    PaymentDataWithRequiredPayee:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentDataWithRequiredPayee"
    CreatedMessageWithContentResponse:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithContentResponse"
    CreatedMessageWithContentAndEnrichedData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithContentAndEnrichedData"
    CreatedMessageWithContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithContent"
    PrescriptionData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PrescriptionData"
    ThirdPartyData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyData"
    HasPrecondition:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/HasPrecondition"
    Ulid:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Ulid"
    LegalData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/LegalData"
    ServiceId:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServiceId"
    MessageStatusReadingChange:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageStatusReadingChange"
    MessageStatusArchivingChange:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageStatusArchivingChange"
    MessageStatusBulkChange:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageStatusBulkChange"
    MessageStatusChange:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageStatusChange"
    ThirdPartyMessageWithContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyMessageWithContent"
    ThirdPartyMessage:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyMessage"
    ThirdPartyAttachment:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyAttachment"
    ThirdPartyMessagePrecondition:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyMessagePrecondition"
    MessageCategory:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageCategory"
    MessageCategoryBase:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageCategoryBase"
    MessageCategoryPayment:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageCategoryPayment"
    MessageCategoryPN:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageCategoryPN"
    PaymentAmount:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentAmount"
    PaymentNoticeNumber:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentNoticeNumber"
   
    # Local definitions
    MessageContentWithAttachments:
      allOf:
        - type: object
          properties:
            attachments:
              type: array
              items:
                $ref: "#/components/schemas/MessageAttachment"
        - $ref: "#/components/schemas/NewMessageContent"
    MessageAttachment:
      type: object
      title: MessageAttachment
      description: Describes a message's attachment
      properties:
        name:
          type: string
        content:
          type: string
        mime_type:
          type: string
      required:
        - name
        - content
        - mime_type
    CreatedMessageWithContentAndAttachments:
      allOf:
        - type: object
          properties:
            content:
              $ref: "#/components/schemas/MessageContentWithAttachments"
          required:
            - content
        - $ref: "#/components/schemas/CreatedMessageWithContentResponse"
    Installation:
      type: object
      title: Installation
      description: Describes an app installation.
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        pushChannel:
          $ref: '#/components/schemas/PushChannel'
      required:
        - platform
        - pushChannel
    Platform:
      type: string
      description: The platform type where the installation happened.
      enum:
        - apns
        - gcm
    PushChannel:
      type: string
      description: |-
        The Push Notification Service handle for this Installation.
        See https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management
    SuccessResponse:
      type: object
      properties:
        message:
          type: string 
    # Payment info definitions from PagoPA ecommerce
    PaymentInfoResponse:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentRequestsGetResponse"  
    # Payment error fault codes
    ValidationFaultPaymentUnknown:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentUnknown"
    ValidationFaultPaymentUnavailable:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentUnavailable"
    ValidationFaultPaymentDataError:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentDataError"
    PaymentOngoingStatusFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentOngoingStatusFault"
    PaymentExpiredStatusFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentExpiredStatusFault"
    PaymentCanceledStatusFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentCanceledStatusFault"
    PaymentDuplicatedStatusFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentDuplicatedStatusFault"
    GatewayFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/GatewayFault"
    PartyConfigurationFault:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PartyConfigurationFault"  
    # Payment response types
    PaymentInfoNotFoundResponse:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentInfoNotFoundResponse"
    PaymentInfoConflictResponse:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentInfoConflictResponse"
    PaymentInfoBadGatewayResponse:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentInfoBadGatewayResponse"
    PaymentInfoUnavailableResponse:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PartyConfigurationFaultPaymentProblemJson"
    # Payment error problem json types
    ValidationFaultPaymentUnknownProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentUnknownProblemJson"
    ValidationFaultPaymentUnavailableProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentUnavailableProblemJson"
    ValidationFaultPaymentDataErrorProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/ValidationFaultPaymentDataErrorProblemJson"
    PaymentOngoingStatusFaultPaymentProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentOngoingStatusFaultPaymentProblemJson"
    PaymentExpiredStatusFaultPaymentProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentExpiredStatusFaultPaymentProblemJson"
    PaymentCanceledStatusFaultPaymentProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentCanceledStatusFaultPaymentProblemJson"
    PaymentDuplicatedStatusFaultPaymentProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/PaymentDuplicatedStatusFaultPaymentProblemJson"
    GatewayFaultPaymentProblemJson:
      $ref: "consumed/pagopa_ecommerce_v3.yaml#/components/schemas/GatewayFaultPaymentProblemJson"
    InstallationID:
      type: string
      minLength: 1
      description: |-
        The sixteen octets of an Installation ID are represented as 32 hexadecimal (base 16) digits, displayed in five groups
        separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 alphanumeric characters and four
        hyphens).
        See https://en.wikipedia.org/wiki/Universally_unique_identifier
    InvalidThirdPartyMessageType:
      type: string
      x-extensible-enum:
        - ATTACHMENTS_NOT_PRESENT
        - REMOTE_CONTENT_NOT_PRESENT
        - MARKDOWN_VALIDATION_ERROR
        - SUBJECT_VALIDATION_ERROR
      description: A representation of all the error type for an invalid ThirdPartyMessage
      example: ATTACHMENTS_NOT_PRESENT
    SendActivation:
      type: object
      properties:
        activation_status:
          type: boolean
      required:
        - activation_status
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
