openapi: 3.0.1
info:
  title: Proxy API
  description: Mobile and web proxy API gateway.
  version: 16.12.1
servers:
  - url: https://api-app.io.pagopa.it/api/v1
security:
  - Bearer: []
paths:
  /services/{service_id}/preferences:
    get:
      summary: GetServicePreferences
      operationId: getServicePreferences
      parameters:
        - name: service_id
          in: path
          description: The ID of an existing Service.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Service Preference found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicePreference'
              example:
                can_access_message_read_status: true
                is_inbox_enabled: true
                is_email_enabled: false
                is_webhook_enabled: true
                settings_version: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
          content: {}
        '404':
          description: No service found for the provided ID.
          content: {}
        '409':
          description: Conflict. The Profile is not in the correct preference mode.
          content: {}
        '429':
          description: Too many requests
          content: {}
        '500':
          description: Internal Server Error
          content: {}
    post:
      summary: UpsertServicePreferences
      operationId: upsertServicePreferences
      parameters:
        - name: service_id
          in: path
          description: The ID of an existing Service.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertServicePreference'
        required: false
      responses:
        '200':
          description: Service Preference found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicePreference'
              example:
                can_access_message_read_status: true
                is_inbox_enabled: true
                is_email_enabled: false
                is_webhook_enabled: true
                settings_version: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
          content: {}
        '404':
          description: No service found for the provided ID.
          content: {}
        '409':
          description: >-
            Conflict. Either the provided preference setting version is not
            consistent with the current version stored in the Profile

            or the Profile is not in the correct preference mode.
          content: {}
        '429':
          description: Too many requests
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /profile:
    get:
      summary: Get user's profile
      description: Returns the profile for the user identified by the provided fiscal code.
      operationId: getUserProfile
      responses:
        '200':
          description: Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializedProfile'
              example:
                email: email@example.com
                family_name: Rossi
                fiscal_code: TMMEXQ60A10Y526X
                has_profile: true
                is_email_set: true
                is_inbox_enabled: true
                is_webhook_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                name: Mario
                spid_email: preferred@example.com
                service_preferences_settings:
                  - mode: LEGACY
                version: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: There was an error in retrieving the user profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
    post:
      summary: Update the User's profile
      description: Update the profile for the user identified by the provided fiscal code.
      operationId: updateProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        '200':
          description: Profile updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializedProfile'
              example:
                email: email@example.com
                family_name: Rossi
                fiscal_code: TMMEXQ60A10Y526X
                has_profile: true
                is_email_set: true
                is_inbox_enabled: true
                is_webhook_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                name: Mario
                spid_email: preferred@example.com
                version: 0
        '400':
          description: Invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '409':
          description: Conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Profile cannot be updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /api-profile:
    get:
      summary: Get user's profile stored into the API
      description: Returns the profile for the user identified by the provided fiscal code.
      operationId: getApiUserProfile
      responses:
        '200':
          description: Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtendedProfile'
              example:
                email: email@example.com
                preferred_languages:
                  - it_IT
                is_inbox_enabled: true
                accepted_tos_version: 1
                is_webhook_enabled: true
                is_email_enabled: true
                is_email_validated: true
                is_email_already_taken: false
                version: 1
                sender_allowed: true
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: There was an error in retrieving the user profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /email-validation-process:
    post:
      summary: Start the Email Validation Process
      description: |-
        Start the email validation process that create the validation token
        and send the validation email
      operationId: startEmailValidationProcess
      responses:
        '202':
          description: Accepted
          content: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: There was an error starting email validation process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /installations/{installationID}:
    put:
      summary: Create or update an Installation
      description: Create or update an Installation to the Azure Notification hub.
      operationId: createOrUpdateInstallation
      parameters:
        - name: installationID
          in: path
          description: The ID of the message.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Installation'
        required: true
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                message: ok
        '401':
          description: Bearer token null or expired.
          content: {}
        '500':
          description: >-
            There was an error in registering the device to the Notification
            Hub.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /sessions:
    get:
      summary: List sessions of a User
      description: Return all the active sessions for an authenticated User.
      operationId: listUserSessions
      responses:
        '200':
          description: Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '500':
          description: Unavailable service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /payment-requests/{rptId}:
    get:
      summary: Get Payment Info
      description: Retrieve information about a payment
      operationId: getPaymentInfo
      parameters:
        - name: rptId
          in: path
          description: Unique identifier for payments.
          required: true
          schema:
            type: string
        - name: test
          in: query
          description: Use test environment of PagoPAClient
          schema:
            type: boolean
      responses:
        '200':
          description: Payment information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequestsGetResponse'
              example:
                importoSingoloVersamento: 200,
                codiceContestoPagamento: ABC123
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '500':
          description: PagoPA services are not available or request is rejected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProblemJson'
        '504':
          description: gateway timeout.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProblemJson'
  /payment-activations:
    post:
      summary: Activate Payment
      description: Require a lock (activation) for a payment
      operationId: activatePayment
      parameters:
        - name: test
          in: query
          description: Use test environment of PagoPAClient
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentActivationsPostRequest'
        required: true
      responses:
        '200':
          description: Payment activation process started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentActivationsPostResponse'
              example:
                importoSingoloVersamento: 200
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '500':
          description: PagoPA services are not available or request is rejected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProblemJson'
        '504':
          description: gateway timeout.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProblemJson'
      x-codegen-request-body-name: body
  /payment-activations/{codiceContestoPagamento}:
    get:
      summary: Get Activation status
      description: Check the activation status to retrieve the paymentId
      operationId: getActivationStatus
      parameters:
        - name: codiceContestoPagamento
          in: path
          description: Transaction Id used to identify the communication flow.
          required: true
          schema:
            type: string
        - name: test
          in: query
          description: Use test environment of PagoPAClient
          schema:
            type: boolean
      responses:
        '200':
          description: Payment information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentActivationsGetResponse'
              example:
                idPagamento: '123455'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '404':
          description: Activation status not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Unavailable service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /user-data-processing:
    post:
      summary: Set User's data processing choices
      description: >-
        Let the authenticated user express his will to retrieve or delete his
        stored data.
      operationId: upsertUserDataProcessing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDataProcessingChoiceRequest'
        required: true
      responses:
        '200':
          description: User Data processing created / updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDataProcessing'
        '400':
          description: Invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Bearer token null or expired.
          content: {}
        '409':
          description: Conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too may requests
          content: {}
        '500':
          description: User Data processing choice cannot be taken in charge.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /user-data-processing/{choice}:
    get:
      summary: Get User's data processing
      description: >-
        Get the user's request to delete or download his stored data by
        providing a kind of choice.
      operationId: getUserDataProcessing
      parameters:
        - name: choice
          in: path
          description: A representation of a user data processing choice
          required: true
          schema:
            type: string
            enum:
              - DOWNLOAD
              - DELETE
      responses:
        '200':
          description: User data processing retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDataProcessing'
        '401':
          description: Bearer token null or expired.
          content: {}
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too many requests
          content: {}
    delete:
      tags:
        - restricted
      summary: Abort User's revious data processing request
      description: Ask for a request to abort, if present
      operationId: abortUserDataProcessing
      parameters:
        - name: choice
          in: path
          description: A representation of a user data processing choice
          required: true
          schema:
            type: string
            enum:
              - DOWNLOAD
              - DELETE
      responses:
        '202':
          description: The abort request has been recorded
          content: {}
        '400':
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
          content: {}
        '404':
          description: Not Found
          content: {}
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '429':
          description: Too many requests
          content: {}
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  schemas:
    AcceptedTosVersion:
      type: number
      minimum: 1
      description: Version of latest terms of service accepted by the user.
    AppVersion:
      type: string
      pattern: ^((0|[1-9]\d*)\.){2}(0|[1-9]\d*)(\.(0|[1-9]\d*)){0,1}$
      description: A string field in Semantic Versioning format
      example: 1.10.11
    BlockedInboxOrChannels:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
          description: |-
            All notification channels plus the message inbox.
            These represent all the possible channels a user could block.
          x-extensible-enum:
            - EMAIL
            - INBOX
            - WEBHOOK
          example: INBOX
      description: |-
        All the notification channels blocked by the user.
        Each channel is related to a specific service (sender).
    DepartmentName:
      type: string
      description: |-
        The department inside the organization that runs the service. Will
        be added to the content of sent messages.
      minLength: 1
    EmailAddress:
      type: string
      format: email
      example: foobar@example.com
    PreferredLanguage:
      type: string
      x-extensible-enum:
        - it_IT
        - en_GB
        - es_ES
        - de_DE
        - fr_FR
      example: it_IT
    PreferredLanguages:
      type: array
      items:
        $ref: '#/components/schemas/PreferredLanguage'
      description: >-
        Indicates the User's preferred written or spoken languages in order

        of preference. Generally used for selecting a localized User interface.
        Valid

        values are concatenation of the ISO 639-1 two letter language code, an
        underscore,

        and the ISO 3166-1 2 letter country code; e.g., 'en_US' specifies the
        language

        English and country US.
    Profile:
      type: object
      description: |-
        Describes the citizen's profile.
        Used for profile update.
      properties:
        email:
          $ref: '#/components/schemas/EmailAddress'
        service_preferences_settings:
          $ref: '#/components/schemas/ServicePreferencesSettings'
        blocked_inbox_or_channels:
          $ref: '#/components/schemas/BlockedInboxOrChannels'
        preferred_languages:
          $ref: '#/components/schemas/PreferredLanguages'
        is_inbox_enabled:
          $ref: '#/components/schemas/IsInboxEnabled'
        accepted_tos_version:
          $ref: '#/components/schemas/AcceptedTosVersion'
        is_webhook_enabled:
          $ref: '#/components/schemas/IsWebhookEnabled'
        is_email_enabled:
          $ref: '#/components/schemas/IsEmailEnabled'
        reminder_status:
          $ref: '#/components/schemas/ReminderStatus'
        last_app_version:
          $ref: '#/components/schemas/AppVersion'
        push_notifications_content_type:
          $ref: '#/components/schemas/PushNotificationsContentType'
        version:
          type: integer
      required:
        - version
    ExtendedProfile:
      description: |-
        Describes the citizen's profile, mostly interesting for preferences
        attributes.
      type: object
      properties:
        email:
          $ref: '#/components/schemas/EmailAddress'
        service_preferences_settings:
          $ref: '#/components/schemas/ServicePreferencesSettings'
        blocked_inbox_or_channels:
          $ref: '#/components/schemas/BlockedInboxOrChannels'
        preferred_languages:
          $ref: '#/components/schemas/PreferredLanguages'
        is_inbox_enabled:
          $ref: '#/components/schemas/IsInboxEnabled'
        accepted_tos_version:
          $ref: '#/components/schemas/AcceptedTosVersion'
        is_webhook_enabled:
          $ref: '#/components/schemas/IsWebhookEnabled'
        is_email_enabled:
          $ref: '#/components/schemas/IsEmailEnabled'
        is_email_validated:
          $ref: '#/components/schemas/IsEmailValidated'
        is_email_already_taken:
          $ref: '#/components/schemas/IsEmailAlreadyTaken'
        reminder_status:
          $ref: '#/components/schemas/ReminderStatus'
        is_test_profile:
          $ref: '#/components/schemas/IsTestProfile'
        last_app_version:
          $ref: '#/components/schemas/AppVersion'
        push_notifications_content_type:
          $ref: '#/components/schemas/PushNotificationsContentType'
        version:
          type: integer
      required:
        - is_email_enabled
        - is_email_validated
        - is_email_already_taken
        - is_inbox_enabled
        - is_webhook_enabled
        - service_preferences_settings
        - version
    FiscalCode:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: '@pagopa/ts-commons/lib/strings'
      example: SPNDNL80R13C555X
    IsEmailEnabled:
      type: boolean
      description: >-
        True if the recipient of a message wants to forward the notifications to
        his email address.
    IsInboxEnabled:
      type: boolean
      description: |-
        True if the recipient of a message wants to store its content for
        later retrieval.
    IsEmailValidated:
      type: boolean
      description: True if the user email has been validated.
    IsEmailAlreadyTaken:
      type: boolean
      default: false
      description: |-
        True if the user email has been validated by another user.
        If so, the user must provide a new email.
    UpdateProfile412ErrorTypes:
      type: string
      description: >-
        List of error types returned by the updateProfile endpoint when the HTTP
        status code is 412
      x-extensible-enum:
        - https://ioapp.it/problems/email-already-taken
      example: https://ioapp.it/problems/email-already-taken
    ReminderStatus:
      type: string
      x-extensible-enum:
        - ENABLED
        - DISABLED
      example: ENABLED
      description: Api definition of reminder opt-in status
    PushNotificationsContentType:
      type: string
      x-extensible-enum:
        - FULL
        - ANONYMOUS
      example: FULL
      description: >-
        This parameter specifies how a specific user wants to visualize push
        notifications.

        FULL leads to descriptive push notifications while ANONYMOUS leads to
        silent ones.
    IsTestProfile:
      type: boolean
      description: True if the user's profile is only for test purpose.
      default: false
    IsWebhookEnabled:
      type: boolean
      description: >-
        True if the recipient of a message wants to forward the notifications to
        the default webhook.
    LimitedProfile:
      description: |-
        Describes the citizen's profile, mostly interesting for preferences
        attributes.
      type: object
      properties:
        sender_allowed:
          type: boolean
          description: |-
            True in case the service that made the request can send
            messages to the user identified by this profile (false otherwise).
        preferred_languages:
          $ref: '#/components/schemas/PreferredLanguages'
      required:
        - sender_allowed
    MessageResponseNotificationStatus:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/NotificationChannelStatusValue'
        webhook:
          $ref: '#/components/schemas/NotificationChannelStatusValue'
    NotificationChannelStatusValue:
      type: string
      description: >-
        The status of a notification (one for each channel).

        "SENT": the notification was succesfully sent to the channel (ie. email
        or push notification)

        "THROTTLED": a temporary failure caused a retry during the notification
        processing;
          the notification associated with this channel will be delayed for a maximum of 7 days or until the message expires
        "EXPIRED": the message expired before the notification could be sent;
          this means that the maximum message time to live was reached; no notification will be sent to this channel
        "FAILED": a permanent failure caused the process to exit with an error,
        no notification will be sent to this channel
      x-extensible-enum:
        - SENT
        - THROTTLED
        - EXPIRED
        - FAILED
      example: SENT
    NotificationChannel:
      type: string
      description: All notification channels.
      x-extensible-enum:
        - EMAIL
        - WEBHOOK
      example: EMAIL
    OrganizationFiscalCode:
      type: string
      description: Organization fiscal code.
      format: OrganizationFiscalCode
      x-import: '@pagopa/ts-commons/lib/strings'
      example: '12345678901'
    OrganizationName:
      type: string
      description: |-
        The organization that runs the service. Will be added to the content
        of sent messages to identify the sender.
      minLength: 1
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 200
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the
            problem.

            It may or may not yield further information if dereferenced.
    ServiceId:
      type: string
      description: |-
        The ID of the Service. Equals the subscriptionId of a registered
        API user.
      minLength: 1
    ServiceCategory:
      x-one-of: true
      allOf:
        - $ref: '#/components/schemas/SpecialServiceCategory'
        - $ref: '#/components/schemas/StandardServiceCategory'
    SpecialServiceCategory:
      type: string
      x-extensible-enum:
        - SPECIAL
    StandardServiceCategory:
      type: string
      x-extensible-enum:
        - STANDARD
    Timestamp:
      type: string
      format: UTCISODateFromString
      description: A date-time field in ISO-8601 format and UTC timezone.
      x-import: '@pagopa/ts-commons/lib/dates'
      example: '2018-10-13T00:00:00.000Z'
    PaymentNoticeNumber:
      description: >-
        The field "Numero Avviso" of pagoPa, needed to identify the payment.
        Format is `<aux digit(1n)>[<application code> (2n)]<codice IUV
        (15|17n)>`. See [pagoPa
        specs](https://docs.pagopa.it/saci/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/premessa)
        for more info on this field and the IUV.
      type: string
      pattern: ^[0123][0-9]{17}$
    PaymentAmount:
      description: >-
        Amount of payment in euro cent. PagoPA accepts up to 9999999999 euro
        cents.
      type: integer
      minimum: 1
      maximum: 9999999999
    PaymentData:
      allOf:
        - type: object
          description: Metadata needed to process pagoPA payments.
          properties:
            amount:
              $ref: '#/components/schemas/PaymentAmount'
            notice_number:
              $ref: '#/components/schemas/PaymentNoticeNumber'
            invalid_after_due_date:
              type: boolean
              default: false
          required:
            - amount
            - notice_number
        - type: object
          properties:
            payee:
              type: object
              description: Metadata needed to explicit payment's payee.
              properties:
                fiscal_code:
                  $ref: '#/components/schemas/OrganizationFiscalCode'
              required:
                - fiscal_code
    TimeToLiveSeconds:
      type: integer
      default: 3600
      minimum: 3600
      maximum: 604800
      description: |-
        This parameter specifies for how long (in seconds) the system will
        try to deliver the message to the channels configured by the user.
      example: 3600
    UserDataProcessingStatus:
      type: string
      description: The status of a user data processing request
      enum:
        - PENDING
        - WIP
        - CLOSED
        - FAILED
        - ABORTED
      example: PENDING
    UserDataProcessingChoice:
      type: string
      description: User's choice to delete or download his own data.
      enum:
        - DOWNLOAD
        - DELETE
      example: DOWNLOAD
    UserDataProcessingChoiceRequest:
      type: object
      description: A request wrapper for User data processing choice
      properties:
        choice:
          $ref: '#/components/schemas/UserDataProcessingChoice'
      required:
        - choice
    UserDataProcessing:
      type: object
      description: A representation of a single user data processing request
      properties:
        choice:
          $ref: '#/components/schemas/UserDataProcessingChoice'
        status:
          $ref: '#/components/schemas/UserDataProcessingStatus'
        created_at:
          $ref: '#/components/schemas/Timestamp'
        updated_at:
          $ref: '#/components/schemas/Timestamp'
        version:
          type: integer
      required:
        - choice
        - status
        - version
    ServicePreferencesSettings:
      description: |-
        Describes the citizen's profile, mostly interesting for preferences
        attributes.
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/ServicesPreferencesMode'
      required:
        - mode
    ServicesPreferencesMode:
      type: string
      enum:
        - LEGACY
        - AUTO
        - MANUAL
    BasicServicePreference:
      description: >-
        Define a set of required preferences of a Citizen for a given Service.

        It's needed by Citizens to express how they want Services to get in
        touch with them.
      type: object
      properties:
        is_email_enabled:
          type: boolean
        is_inbox_enabled:
          type: boolean
        is_webhook_enabled:
          type: boolean
        settings_version:
          type: integer
          minimum: 0
      required:
        - is_email_enabled
        - is_inbox_enabled
        - is_webhook_enabled
        - settings_version
    ServicePreference:
      description: |-
        Return the set of preferences of a Citizen for a given Service.
        It's needed by Citizens to read previoulsy expressed preferences.
      allOf:
        - $ref: '#/components/schemas/BasicServicePreference'
        - type: object
          properties:
            can_access_message_read_status:
              type: boolean
          required:
            - can_access_message_read_status
    UpsertServicePreference:
      description: >-
        Define a set of preferences of a Citizen for a given Service.

        Extends the BasicServicePreference with new optional preferences for
        backward compatibility.
      allOf:
        - $ref: '#/components/schemas/BasicServicePreference'
        - type: object
          properties:
            can_access_message_read_status:
              type: boolean
    PaginationResponse:
      type: object
      description: Pagination response parameters.
      properties:
        prev:
          type: string
          description: Contains a value useful to get the previous page
          example: first_id_of_the_page
        next:
          type: string
          description: Contains a value useful to get the next page
          example: last_id_of_the_page
    Ulid:
      type: string
      description: Ulid string.
      format: Ulid
      x-import: '@pagopa/ts-commons/lib/strings'
      example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
    PathTraversalSafePathParam:
      description: >-
        A non empty string that is safe to be used in an url parameter to avoid
        path traversal attacks
      type: string
      pattern: ^[0-9a-zA-Z\-\._\/+]+$
    PaymentProblemJson:
      description: >-
        A ProblemJson-like type specific for the GetPayment and ActivatePayment
        operations
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
        detail:
          description: >-
            DEPRECATED. Fault codes for the PagoPA Verifica and Attiva
            operations.

            Possible fault codes are:

            - `PAYMENT_DUPLICATED`

            - `INVALID_AMOUNT`

            - `PAYMENT_ONGOING`

            - `PAYMENT_EXPIRED`

            - `PAYMENT_UNAVAILABLE`

            - `PAYMENT_UNKNOWN`

            - `DOMAIN_UNKNOWN`

            - `PPT_MULTI_BENEFICIARIO`

            - `GENERIC_ERROR`
          type: string
          x-extensible-enum:
            - PAYMENT_DUPLICATED
            - INVALID_AMOUNT
            - PAYMENT_ONGOING
            - PAYMENT_EXPIRED
            - PAYMENT_UNAVAILABLE
            - PAYMENT_UNKNOWN
            - DOMAIN_UNKNOWN
            - PPT_MULTI_BENEFICIARIO
            - GENERIC_ERROR
        detail_v2:
          description: >-
            This enumeration includes all possible fault codes for the
            PagoPA/Controparte Verifica
            ([`getPaymentInfo`](#/default/getPaymentInfo)) and Attiva
            ([`activatePayment`](#/default/activatePayment)) operations.

            For further information visit
            https://docs.pagopa.it/gestionedeglierrori/struttura-degli-errori/fault-code.

            Possible fault codes are:
              - `PPT_SYSTEM_ERROR`
              - `PPT_AUTORIZZAZIONE`
              - `PPT_AUTENTICAZIONE`
              - `PPT_SINTASSI_XSD`
              - `PPT_SINTASSI_EXTRAXSD`
              - `PPT_SEMANTICA`
              - `PPT_RPT_DUPLICATA`
              - `PPT_RPT_SCONOSCIUTA`
              - `PPT_RT_SCONOSCIUTA`
              - `PPT_RT_NONDISPONIBILE`
              - `PPT_SUPERAMENTOSOGLIA`
              - `PPT_SEGREGAZIONE`
              - `PPT_TIPOFIRMA_SCONOSCIUTO`
              - `PPT_ERRORE_FORMATO_BUSTA_FIRMATA`
              - `PPT_FIRMA_INDISPONIBILE`
              - `PPT_ID_CARRELLO_DUPLICATO`
              - `PPT_OPER_NON_STORNABILE`
              - `PPT_OPER_NON_REVOCABILE`
              - `PPT_WISP_TIMEOUT_RECUPERO_SCELTA`
              - `PPT_WISP_SESSIONE_SCONOSCIUTA`
              - `PPT_CANALE_ERRORE`
              - `PPT_CODIFICA_PSP_SCONOSCIUTA`
              - `PPT_PSP_SCONOSCIUTO`
              - `PPT_PSP_DISABILITATO`
              - `PPT_TIPO_VERSAMENTO_SCONOSCIUTO`
              - `PPT_INTERMEDIARIO_PSP_SCONOSCIUTO`
              - `PPT_INTERMEDIARIO_PSP_DISABILITATO`
              - `PPT_CANALE_IRRAGGIUNGIBILE`
              - `PPT_CANALE_SERVIZIO_NONATTIVO`
              - `PPT_CANALE_TIMEOUT`
              - `PPT_CANALE_NONRISOLVIBILE`
              - `PPT_CANALE_INDISPONIBILE`
              - `PPT_CANALE_SCONOSCIUTO`
              - `PPT_CANALE_DISABILITATO`
              - `PPT_CANALE_ERR_PARAM_PAG_IMM`
              - `PPT_CANALE_ERRORE_RESPONSE`
              - `PPT_RT_DUPLICATA`
              - `PPT_ISCRIZIONE_NON_PRESENTE`
              - `PPT_ULTERIORE_ISCRIZIONE`
              - `PPT_PDD_IRRAGGIUNGIBILE`
              - `PPT_ERRORE_EMESSO_DA_PAA`
              - `PPT_DOMINIO_SCONOSCIUTO`
              - `PPT_DOMINIO_DISABILITATO`
              - `PPT_INTERMEDIARIO_PA_SCONOSCIUTO`
              - `PPT_INTERMEDIARIO_PA_DISABILITATO`
              - `PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE`
              - `PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO`
              - `PPT_STAZIONE_INT_PA_ERRORE_RESPONSE`
              - `PPT_STAZIONE_INT_PA_TIMEOUT`
              - `PPT_STAZIONE_INT_PA_NONRISOLVIBILE`
              - `PPT_STAZIONE_INT_PA_INDISPONIBILE`
              - `PPT_STAZIONE_INT_PA_SCONOSCIUTA`
              - `PPT_STAZIONE_INT_PA_DISABILITATA`
              - `PPT_ID_FLUSSO_SCONOSCIUTO`
              - `PAA_ID_DOMINIO_ERRATO`
              - `PAA_ID_INTERMEDIARIO_ERRATO`
              - `PAA_STAZIONE_INT_ERRATA`
              - `PAA_RPT_SCONOSCIUTA`
              - `PAA_RT_DUPLICATA`
              - `PAA_TIPOFIRMA_SCONOSCIUTO`
              - `PAA_ERRORE_FORMATO_BUSTA_FIRMATA`
              - `PAA_FIRMA_INDISPONIBILE`
              - `PAA_FIRMA_ERRATA`
              - `PAA_PAGAMENTO_SCONOSCIUTO`
              - `PAA_PAGAMENTO_DUPLICATO`
              - `PAA_PAGAMENTO_IN_CORSO`
              - `PAA_PAGAMENTO_ANNULLATO`
              - `PAA_PAGAMENTO_SCADUTO`
              - `PAA_SINTASSI_XSD`
              - `PAA_SINTASSI_EXTRAXSD`
              - `PAA_SEMANTICA`
              - `PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO`
              - `PAA_SYSTEM_ERROR`
              - `CANALE_SINTASSI_XSD`
              - `CANALE_SINTASSI_EXTRAXSD`
              - `CANALE_SEMANTICA`
              - `CANALE_RPT_DUPLICATA`
              - `CANALE_RPT_SCONOSCIUTA`
              - `CANALE_RPT_RIFIUTATA`
              - `CANALE_RT_SCONOSCIUTA`
              - `CANALE_RT_NON_DISPONIBILE`
              - `CANALE_INDISPONIBILE`
              - `CANALE_RICHIEDENTE_ERRATO`
              - `CANALE_SYSTEM_ERROR`
              - `PPT_LOCAL_ERROR_PROTOCOLLO`
              - `PPT_LOCAL_ERROR_EXTRAXSD`
              - `PPT_LOCAL_ERROR_FSM`
              - `PPT_RT_SEGNO_DISCORDE`
              - `CANALE_FIRMA_SCONOSCIUTA`
              - `CANALE_BUSTA_ERRATA`
              - `CANALE_NEGA_CONTABILIZZAZIONE`
              - `CANALE_CARRELLO_DUPLICATO_KO`
              - `CANALE_CARRELLO_DUPLICATO_UNKNOWN`
              - `CANALE_CARRELLO_DUPLICATO_OK`
              - `OGGETTO_DISABILITATO`
              - `PPT_IBAN_NON_CENSITO`
              - `PPT_RT_IN_GESTIONE`
              - `CANALE_CONVENZIONE_NON_VALIDA`
              - `PAA_CONVENZIONE_NON_VALIDA`
              - `PPT_IMPORTO_ERRATO`
              - `PPT_TOKEN_SCONOSCIUTO`
              - `PPT_TOKEN_SCADUTO`
              - `PPT_POSIZIONE_SCONOSCIUTA`
              - `PPT_DATI_POSIZIONE_GIA_CONOSCIUTI`
              - `PPT_ESITO_GIA_ACQUISITO`
              - `PPT_PAGAMENTO_IN_CORSO`
              - `PPT_PAGAMENTO_DUPLICATO`
              - `PPT_MULTI_BENEFICIARIO`
              - `PPT_ERRORE`
              - `GENERIC_ERROR`
          type: string
          x-extensible-enum:
            - PPT_SYSTEM_ERROR
            - PPT_AUTORIZZAZIONE
            - PPT_AUTENTICAZIONE
            - PPT_SINTASSI_XSD
            - PPT_SINTASSI_EXTRAXSD
            - PPT_SEMANTICA
            - PPT_RPT_DUPLICATA
            - PPT_RPT_SCONOSCIUTA
            - PPT_RT_SCONOSCIUTA
            - PPT_RT_NONDISPONIBILE
            - PPT_SUPERAMENTOSOGLIA
            - PPT_SEGREGAZIONE
            - PPT_TIPOFIRMA_SCONOSCIUTO
            - PPT_ERRORE_FORMATO_BUSTA_FIRMATA
            - PPT_FIRMA_INDISPONIBILE
            - PPT_ID_CARRELLO_DUPLICATO
            - PPT_OPER_NON_STORNABILE
            - PPT_OPER_NON_REVOCABILE
            - PPT_WISP_TIMEOUT_RECUPERO_SCELTA
            - PPT_WISP_SESSIONE_SCONOSCIUTA
            - PPT_CANALE_ERRORE
            - PPT_CODIFICA_PSP_SCONOSCIUTA
            - PPT_PSP_SCONOSCIUTO
            - PPT_PSP_DISABILITATO
            - PPT_TIPO_VERSAMENTO_SCONOSCIUTO
            - PPT_INTERMEDIARIO_PSP_SCONOSCIUTO
            - PPT_INTERMEDIARIO_PSP_DISABILITATO
            - PPT_CANALE_IRRAGGIUNGIBILE
            - PPT_CANALE_SERVIZIO_NONATTIVO
            - PPT_CANALE_TIMEOUT
            - PPT_CANALE_NONRISOLVIBILE
            - PPT_CANALE_INDISPONIBILE
            - PPT_CANALE_SCONOSCIUTO
            - PPT_CANALE_DISABILITATO
            - PPT_CANALE_ERR_PARAM_PAG_IMM
            - PPT_CANALE_ERRORE_RESPONSE
            - PPT_RT_DUPLICATA
            - PPT_ISCRIZIONE_NON_PRESENTE
            - PPT_ULTERIORE_ISCRIZIONE
            - PPT_PDD_IRRAGGIUNGIBILE
            - PPT_ERRORE_EMESSO_DA_PAA
            - PPT_DOMINIO_SCONOSCIUTO
            - PPT_DOMINIO_DISABILITATO
            - PPT_INTERMEDIARIO_PA_SCONOSCIUTO
            - PPT_INTERMEDIARIO_PA_DISABILITATO
            - PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE
            - PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO
            - PPT_STAZIONE_INT_PA_ERRORE_RESPONSE
            - PPT_STAZIONE_INT_PA_TIMEOUT
            - PPT_STAZIONE_INT_PA_NONRISOLVIBILE
            - PPT_STAZIONE_INT_PA_INDISPONIBILE
            - PPT_STAZIONE_INT_PA_SCONOSCIUTA
            - PPT_STAZIONE_INT_PA_DISABILITATA
            - PPT_ID_FLUSSO_SCONOSCIUTO
            - PAA_ID_DOMINIO_ERRATO
            - PAA_ID_INTERMEDIARIO_ERRATO
            - PAA_STAZIONE_INT_ERRATA
            - PAA_RPT_SCONOSCIUTA
            - PAA_RT_DUPLICATA
            - PAA_TIPOFIRMA_SCONOSCIUTO
            - PAA_ERRORE_FORMATO_BUSTA_FIRMATA
            - PAA_FIRMA_INDISPONIBILE
            - PAA_FIRMA_ERRATA
            - PAA_PAGAMENTO_SCONOSCIUTO
            - PAA_PAGAMENTO_DUPLICATO
            - PAA_PAGAMENTO_IN_CORSO
            - PAA_PAGAMENTO_ANNULLATO
            - PAA_PAGAMENTO_SCADUTO
            - PAA_SINTASSI_XSD
            - PAA_SINTASSI_EXTRAXSD
            - PAA_SEMANTICA
            - PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO
            - PAA_SYSTEM_ERROR
            - CANALE_SINTASSI_XSD
            - CANALE_SINTASSI_EXTRAXSD
            - CANALE_SEMANTICA
            - CANALE_RPT_DUPLICATA
            - CANALE_RPT_SCONOSCIUTA
            - CANALE_RPT_RIFIUTATA
            - CANALE_RT_SCONOSCIUTA
            - CANALE_RT_NON_DISPONIBILE
            - CANALE_INDISPONIBILE
            - CANALE_RICHIEDENTE_ERRATO
            - CANALE_SYSTEM_ERROR
            - PPT_LOCAL_ERROR_PROTOCOLLO
            - PPT_LOCAL_ERROR_EXTRAXSD
            - PPT_LOCAL_ERROR_FSM
            - PPT_RT_SEGNO_DISCORDE
            - CANALE_FIRMA_SCONOSCIUTA
            - CANALE_BUSTA_ERRATA
            - CANALE_NEGA_CONTABILIZZAZIONE
            - CANALE_CARRELLO_DUPLICATO_KO
            - CANALE_CARRELLO_DUPLICATO_UNKNOWN
            - CANALE_CARRELLO_DUPLICATO_OK
            - OGGETTO_DISABILITATO
            - PPT_IBAN_NON_CENSITO
            - PPT_RT_IN_GESTIONE
            - CANALE_CONVENZIONE_NON_VALIDA
            - PAA_CONVENZIONE_NON_VALIDA
            - PPT_IMPORTO_ERRATO
            - PPT_TOKEN_SCONOSCIUTO
            - PPT_TOKEN_SCADUTO
            - PPT_POSIZIONE_SCONOSCIUTA
            - PPT_DATI_POSIZIONE_GIA_CONOSCIUTI
            - PPT_ESITO_GIA_ACQUISITO
            - PPT_PAGAMENTO_IN_CORSO
            - PPT_PAGAMENTO_DUPLICATO
            - PPT_MULTI_BENEFICIARIO
            - PPT_ERRORE
            - GENERIC_ERROR
        instance:
          type: string
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the
            problem.

            It may or may not yield further information if dereferenced.
      required:
        - detail
        - detail_v2
    CodiceContestoPagamento:
      description: Transaction Id used to identify the communication flow
      type: string
      minLength: 32
      maxLength: 32
    EnteBeneficiario:
      description: Beneficiary institution related to a payment
      type: object
      properties:
        identificativoUnivocoBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        denominazioneBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        codiceUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        denomUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        indirizzoBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        civicoBeneficiario:
          type: string
          minLength: 1
          maxLength: 16
        capBeneficiario:
          type: string
          minLength: 1
          maxLength: 16
        localitaBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        provinciaBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        nazioneBeneficiario:
          type: string
          pattern: '[A-Z]{2}'
      required:
        - identificativoUnivocoBeneficiario
        - denominazioneBeneficiario
    Iban:
      type: string
      pattern: '[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{1,30}'
    ImportoEuroCents:
      description: Amount for payments, in eurocents
      type: integer
      minimum: 0
      maximum: 99999999
    PaymentActivationsGetResponse:
      type: object
      description: >-
        Define the response to send to App to provide the payment activation
        status related to a codiceContestoPagamento
      properties:
        idPagamento:
          type: string
          minLength: 1
          maxLength: 36
      required:
        - idPagamento
    PaymentActivationsPostRequest:
      type: object
      description: Define the request received from CD App to require a payment activation
      properties:
        rptId:
          $ref: '#/components/schemas/RptId'
        importoSingoloVersamento:
          $ref: '#/components/schemas/ImportoEuroCents'
        codiceContestoPagamento:
          $ref: '#/components/schemas/CodiceContestoPagamento'
      required:
        - rptId
        - importoSingoloVersamento
        - codiceContestoPagamento
      example:
        rptId: string
        importoSingoloVersamento: 0
        codiceContestoPagamento: string
    PaymentActivationsPostResponse:
      type: object
      description: Define the response to send to CD App containing activation information
      properties:
        importoSingoloVersamento:
          $ref: '#/components/schemas/ImportoEuroCents'
        ibanAccredito:
          $ref: '#/components/schemas/Iban'
        causaleVersamento:
          type: string
          minLength: 1
          maxLength: 140
        enteBeneficiario:
          $ref: '#/components/schemas/EnteBeneficiario'
        spezzoniCausaleVersamento:
          $ref: '#/components/schemas/SpezzoniCausaleVersamento'
      required:
        - importoSingoloVersamento
    PaymentRequestsGetResponse:
      type: object
      title: PaymentRequestsGetResponse
      description: Define the response to send to CD App containing payment information
      properties:
        importoSingoloVersamento:
          $ref: '#/components/schemas/ImportoEuroCents'
        codiceContestoPagamento:
          $ref: '#/components/schemas/CodiceContestoPagamento'
        ibanAccredito:
          $ref: '#/components/schemas/Iban'
        causaleVersamento:
          type: string
          minLength: 1
          maxLength: 140
        enteBeneficiario:
          $ref: '#/components/schemas/EnteBeneficiario'
        spezzoniCausaleVersamento:
          $ref: '#/components/schemas/SpezzoniCausaleVersamento'
        dueDate:
          type: string
          pattern: ([0-9]{4})-(1[0-2]|0[1-9])-(0[1-9]|1[0-9]|2[0-9]|3[0-1])
          example: '2025-07-31'
      required:
        - importoSingoloVersamento
        - codiceContestoPagamento
    RptId:
      type: string
    SpezzoneStrutturatoCausaleVersamento:
      description: Amount related to a single element of a payment installments
      type: object
      properties:
        causaleSpezzone:
          type: string
          minLength: 1
          maxLength: 25
        importoSpezzone:
          $ref: '#/components/schemas/ImportoEuroCents'
    SpezzoniCausaleVersamento:
      description: Payment installments (optional)
      type: array
      items:
        $ref: '#/components/schemas/SpezzoniCausaleVersamentoItem'
    SpezzoniCausaleVersamentoItem:
      description: Single element of a payment installments
      type: object
      properties:
        spezzoneCausaleVersamento:
          type: string
          minLength: 1
          maxLength: 35
        spezzoneStrutturatoCausaleVersamento:
          $ref: '#/components/schemas/SpezzoneStrutturatoCausaleVersamento'
    AssertionRefSha256:
      type: string
      pattern: ^(sha256-[A-Za-z0-9-_=]{1,44})$
    AssertionRefSha384:
      type: string
      pattern: ^(sha384-[A-Za-z0-9-_=]{1,66})$
    AssertionRefSha512:
      type: string
      pattern: ^(sha512-[A-Za-z0-9-_=]{1,88})$
    AssertionRef:
      x-one-of: true
      allOf:
        - $ref: '#/components/schemas/AssertionRefSha512'
        - $ref: '#/components/schemas/AssertionRefSha384'
        - $ref: '#/components/schemas/AssertionRefSha256'
    Installation:
      type: object
      title: Installation
      description: Describes an app installation.
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        pushChannel:
          $ref: '#/components/schemas/PushChannel'
      required:
        - platform
        - pushChannel
    InitializedProfile:
      type: object
      title: Initialized profile
      description: >-
        Describes the user's profile after it has been stored in the Profile
        API.
      properties:
        accepted_tos_version:
          $ref: '#/components/schemas/AcceptedTosVersion'
        email:
          $ref: '#/components/schemas/EmailAddress'
        blocked_inbox_or_channels:
          $ref: '#/components/schemas/BlockedInboxOrChannels'
        preferred_languages:
          $ref: '#/components/schemas/PreferredLanguages'
        is_inbox_enabled:
          $ref: '#/components/schemas/IsInboxEnabled'
        is_email_validated:
          $ref: '#/components/schemas/IsEmailValidated'
        is_email_already_taken:
          $ref: '#/components/schemas/IsEmailAlreadyTaken'
        is_email_enabled:
          $ref: '#/components/schemas/IsEmailEnabled'
        reminder_status:
          $ref: '#/components/schemas/ReminderStatus'
        push_notifications_content_type:
          $ref: '#/components/schemas/PushNotificationsContentType'
        is_webhook_enabled:
          $ref: '#/components/schemas/IsWebhookEnabled'
        family_name:
          type: string
        fiscal_code:
          $ref: '#/components/schemas/FiscalCode'
        has_profile:
          $ref: '#/components/schemas/HasProfile'
        last_app_version:
          $ref: '#/components/schemas/AppVersion'
        name:
          type: string
        spid_email:
          $ref: '#/components/schemas/EmailAddress'
        date_of_birth:
          type: string
          format: date
        service_preferences_settings:
          $ref: '#/components/schemas/ServicePreferencesSettings'
        version:
          $ref: '#/components/schemas/Version'
      required:
        - family_name
        - fiscal_code
        - has_profile
        - is_inbox_enabled
        - is_email_enabled
        - is_webhook_enabled
        - name
        - service_preferences_settings
        - version
    SessionInfo:
      type: object
      title: Session info of a user
      description: Decribe a session of an authenticated user.
      properties:
        createdAt:
          $ref: '#/components/schemas/Timestamp'
        sessionToken:
          type: string
      required:
        - createdAt
        - sessionToken
    SessionsList:
      description: Contains all active sessions for an authenticated user.
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionInfo'
      required:
        - sessions
    InstallationID:
      type: string
      description: >-
        The sixteen octets of an Installation ID are represented as 32
        hexadecimal (base 16) digits, displayed in five groups

        separated by hyphens, in the form 8-4-4-4-12 for a total of 36
        characters (32 alphanumeric characters and four

        hyphens).

        See https://en.wikipedia.org/wiki/Universally_unique_identifier
      minLength: 1
    HasProfile:
      type: boolean
      default: false
      description: True if the user has a remote profile.
    IsEmailSet:
      type: boolean
      default: false
      description: True if the user has presonalized the email.
    Version:
      type: integer
      description: The entity version.
    Platform:
      type: string
      description: The platform type where the installation happened.
      x-extensible-enum:
        - apns
        - gcm
    PushChannel:
      type: string
      description: >-
        The Push Notification Service handle for this Installation.

        See
        https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management
    SpidLevel:
      type: string
      description: A SPID level.
      x-extensible-enum:
        - https://www.spid.gov.it/SpidL1
        - https://www.spid.gov.it/SpidL2
        - https://www.spid.gov.it/SpidL3
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    LimitedFederatedUser:
      title: Federated user
      description: User data needed by federated applications.
      type: object
      properties:
        fiscal_code:
          $ref: '#/components/schemas/FiscalCode'
      required:
        - fiscal_code
    FederatedUser:
      title: Federated user
      description: User data needed by federated applications.
      allOf:
        - type: object
          properties:
            name:
              type: string
            family_name:
              type: string
          required:
            - name
            - family_name
        - $ref: '#/components/schemas/LimitedFederatedUser'
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
